### ISSUE TITLE
Setup not working: Failed to load schema from

### ISSUE THREAD

**Issue by Maybach91** [swellstores/swell-next-graphql-example#1]
I tried to setup the project according to the README.md. I added the public keys and the store id of my swell store. But when running `pnpm dev` i get the following error:

```

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
✔ Parse Configuration
⚠ Generate outputs
  ❯ Generate to ./src/__generated__/sdk.ts
    ✖
      Failed to load schema from STORE-ID:
      Unable to find any GraphQL type definitions for the following pointers:
      - STORE-ID
      Error:
      Unable to find any GraphQL type definitions for the following pointers:
      - STORE-ID
      at prepareResult (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/@graphql-tools+load@7.8.14_graphql@16.6.0/node_modules/@graphql-tools/load/cjs/load-t…
      at loadTypedefs (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/@graphql-tools+load@7.8.14_graphql@16.6.0/node_modules/@graphql-tools/load/cjs/load-ty…
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadSchema (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/@graphql-tools+load@7.8.14_graphql@16.6.0/node_modules/@graphql-tools/load/cjs/sch…
      at async loadSchema (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/@graphql-codegen+cli@3.3.1_@babel+core@7.21.8_@types+node@18.15.11_graphql@16.6.0/…
      at async /Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/@graphql-codegen+cli@3.3.1_@babel+core@7.21.8_@types+node@18.15.11_graphql@16.6.0/node_modules…
      at async /Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/@graphql-codegen+cli@3.3.1_@babel+core@7.21.8_@types+node@18.15.11_graphql@16.6.0/node_modules…
      at async /Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/@graphql-codegen+cli@3.3.1_@babel+core@7.21.8_@types+node@18.15.11_graphql@16.6.0/node_modules…
      at async Task.run (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/listr2@4.0.5/node_modules/listr2/dist/index.cjs:979:11)
      at async /Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22
      GraphQL Code Generator supports:
      - ES Modules and CommonJS exports (export as default or named export "schema")
      - Introspection JSON File
      - URL of GraphQL endpoint
      - Multiple files with type definitions (glob expression)
      - String in config file
      Try to use one of above options and run codegen again.
    ◼ Load GraphQL documents
    ◼ Generate
  ℹ Watching for changes in /Users/p/Downloads/_Arc/swell-next-graphql-example-main...
event - compiled client and server successfully in 281 ms (170 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 247 ms (181 modules)
error - Error [TypeError]: Only absolute URLs are supported
    at getNodeRequestOptions (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/node-fetch/index.js:1:63531)
    at /Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/node-fetch/index.js:1:65062
    at new Promise (<anonymous>)
    at fetch (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/node-fetch/index.js:1:64996)
    at fetch (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/cross-fetch@3.1.6/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
    at file:///Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/graphql-request@6.1.0_graphql@16.6.0/node_modules/graphql-request/build/esm/index.js:101:18
    at makeRequest (file:///Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/graphql-request@6.1.0_graphql@16.6.0/node_modules/graphql-request/build/esm/index.js:254:28)
    at GraphQLClient.rawRequest (file:///Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/graphql-request@6.1.0_graphql@16.6.0/node_modules/graphql-request/build/esm/index.js:122:20)
    at eval (webpack-internal:///./src/__generated__/sdk.ts:133:64)
    at defaultWrapper (webpack-internal:///./src/__generated__/sdk.ts:127:66)
    at Object.getAllProducts (webpack-internal:///./src/__generated__/sdk.ts:133:20)
    at getStaticProps (webpack-internal:///./src/pages/index.tsx:15:81)
    at /Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/render.js:419:20
    at /Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/trace/tracer.js:92:36
    at NoopContextManager.with (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
    at /Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/trace/tracer.js:81:107
    at NoopContextManager.with (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NextTracerImpl.trace (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/trace/tracer.js:81:32)
    at Object.renderToHTML (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/render.js:414:51)
    at async doRender (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:936:34)
    at async cacheEntry1.responseCache.get.incrementalCache.incrementalCache (/Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1059:28)
    at async /Users/p/Downloads/_Arc/swell-next-graphql-example-main/node_modules/.pnpm/next@13.3.0_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/response-cache/index.js:83:36 {
  digest: undefined
}

```

**Comment by Maybach91** [comment]
This partially is fixed by #2 

After #2 i can see the store, but i still have the error for the `Unable to find any GraphQL type definitions for the following pointers:`.
